debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.mstjang.boardtest: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: board_test
    password: 1q2w3e4!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true   # 테스트용 데이터베이스 띄울때 data.sql
    hibernate:
      ddl-auto: create
#    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100     # 한번에 벌크로 in query 로 n plus query
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

---

spring:
  config:
    activate:
      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#
#  sql:
#    init:
#      mode: always
#  test.database.replace: none